# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Alpaca < Formula
  desc "Lightweight llama-server wrapper for macOS"
  homepage "https://github.com/d2verb/alpaca"
  version "0.0.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/d2verb/alpaca/releases/download/v0.0.1/alpaca_0.0.1_darwin_amd64.tar.gz"
      sha256 "58d99414165cde1d352760012f3b968c2abd2c63d841f24326d2f5280e976fe6"

      def install
        bin.install "alpaca"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/d2verb/alpaca/releases/download/v0.0.1/alpaca_0.0.1_darwin_arm64.tar.gz"
      sha256 "9abfff20ee672c33817e8041d8bac33462ea49a590a71765ec73ead6f37582a9"

      def install
        bin.install "alpaca"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/d2verb/alpaca/releases/download/v0.0.1/alpaca_0.0.1_linux_amd64.tar.gz"
      sha256 "d1bd7e98524475fac741531122f774312015e0e77f268a294597403d94b594ac"
      def install
        bin.install "alpaca"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/d2verb/alpaca/releases/download/v0.0.1/alpaca_0.0.1_linux_arm64.tar.gz"
      sha256 "ccac4ad0db74dcda146b93aa0dcc72e52646d6840607a04337105d245152ee1b"
      def install
        bin.install "alpaca"
      end
    end
  end
end
