# This file was generated by GoReleaser. DO NOT EDIT.
cask "alpaca" do
  name "alpaca"
  desc "Lightweight llama-server wrapper for macOS"
  homepage "https://github.com/d2verb/alpaca"
  version "0.0.2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "alpaca"

  on_macos do
    on_intel do
      url "https://github.com/d2verb/alpaca/releases/download/v#{version}/alpaca_#{version}_darwin_amd64.tar.gz"
      sha256 "882bd5ba091ad6f0351b0714eeb10baf5f0191ea155a4bf6a8479a0343ab7c74"
    end
    on_arm do
      url "https://github.com/d2verb/alpaca/releases/download/v#{version}/alpaca_#{version}_darwin_arm64.tar.gz"
      sha256 "1ef90fa5a3e7072fd83c39600bc5971dea1f0b2c3e1c90e38125f9e662cb887a"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/d2verb/alpaca/releases/download/v#{version}/alpaca_#{version}_linux_amd64.tar.gz"
      sha256 "2cb90d3bee12b7c3af2979db6bb34b83ef03d81beb89cddd64cb56331037c808"
    end
    on_arm do
      url "https://github.com/d2verb/alpaca/releases/download/v#{version}/alpaca_#{version}_linux_arm64.tar.gz"
      sha256 "54daf766c36e287fbf2ab46d50655ae058f4395a7cdda1a6c3ac153c61e713f1"
    end
  end

  postflight do
    require "digest"
    require "json"
    require "fileutils"

    receipt_dir = "#{ENV["HOME"]}/.alpaca"
    FileUtils.mkdir_p(receipt_dir)

    binary_path = "#{staged_path}/alpaca"
    fingerprint = Digest::SHA256.file(binary_path).hexdigest
    timestamp = Time.now.utc.iso8601

    receipt = {
      schema_version: 1,
      install_source: "brew",
      installed_at: timestamp,
      binary_path: binary_path,
      binary_fingerprint: "sha256:#{fingerprint}"
    }

    File.write("#{receipt_dir}/install.json", JSON.pretty_generate(receipt))
  end

  # No zap stanza required
end
