# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Alpaca < Formula
  desc "Lightweight llama-server wrapper for macOS"
  homepage "https://github.com/d2verb/alpaca"
  version "0.0.5"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/d2verb/alpaca/releases/download/v0.0.5/alpaca_0.0.5_darwin_amd64.tar.gz"
      sha256 "911acc7f3c9a521ce89a6f94f2b9bdef6661c52ebb31c610a738f62500769b55"

      def install
        bin.install "alpaca"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/d2verb/alpaca/releases/download/v0.0.5/alpaca_0.0.5_darwin_arm64.tar.gz"
      sha256 "30fc0127d0a26af114ec8ab8c43ee139e82c3a87e6073ffc8f1bca9a75f9ddcc"

      def install
        bin.install "alpaca"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/d2verb/alpaca/releases/download/v0.0.5/alpaca_0.0.5_linux_amd64.tar.gz"
      sha256 "f8a82fd19a35c32aacc61463d4ebe9fe7322e33fbdf1f76a987cf7cdbc8911ea"
      def install
        bin.install "alpaca"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/d2verb/alpaca/releases/download/v0.0.5/alpaca_0.0.5_linux_arm64.tar.gz"
      sha256 "364d3a7dfe297234e275500ee02b9e60ff24ba2a06604494a6d53ffa9c9ce404"
      def install
        bin.install "alpaca"
      end
    end
  end
end
