# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Alpaca < Formula
  desc "Lightweight llama-server wrapper for macOS"
  homepage "https://github.com/d2verb/alpaca"
  version "0.0.15"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/d2verb/alpaca/releases/download/v0.0.15/alpaca_0.0.15_darwin_amd64.tar.gz"
      sha256 "573556ee590b31c185269edb8899890decc69979246fd34b31801ebbab8a4577"

      define_method(:install) do
        bin.install "alpaca"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/d2verb/alpaca/releases/download/v0.0.15/alpaca_0.0.15_darwin_arm64.tar.gz"
      sha256 "04f64b710a43a3889d3dea939830ec744416428508dea425fdef2bc19bb31a47"

      define_method(:install) do
        bin.install "alpaca"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/d2verb/alpaca/releases/download/v0.0.15/alpaca_0.0.15_linux_amd64.tar.gz"
      sha256 "49dfed4155ce736df3dd196cefaa6b76102597ad75336b6a46f13007b3637749"
      define_method(:install) do
        bin.install "alpaca"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/d2verb/alpaca/releases/download/v0.0.15/alpaca_0.0.15_linux_arm64.tar.gz"
      sha256 "281c2ef11e294ae091a6cd71cef06d3220ad0729f2efb76d3338b6eb4dac8d34"
      define_method(:install) do
        bin.install "alpaca"
      end
    end
  end
end
