# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Alpaca < Formula
  desc "Lightweight llama-server wrapper for macOS"
  homepage "https://github.com/d2verb/alpaca"
  version "0.0.13"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/d2verb/alpaca/releases/download/v0.0.13/alpaca_0.0.13_darwin_amd64.tar.gz"
      sha256 "901db43853e9bb6836877fec9245db47a5ec96e538ce5c466f73776acaecea4a"

      def install
        bin.install "alpaca"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/d2verb/alpaca/releases/download/v0.0.13/alpaca_0.0.13_darwin_arm64.tar.gz"
      sha256 "08f83df83dbb9020f0822106d82e8a5156fd6c5b930fc7f24074712c504ed408"

      def install
        bin.install "alpaca"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/d2verb/alpaca/releases/download/v0.0.13/alpaca_0.0.13_linux_amd64.tar.gz"
      sha256 "1deb73e1cd3d0e932d04cc45f7c3376da886b41ecf494a2b5348896675c6a711"
      def install
        bin.install "alpaca"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/d2verb/alpaca/releases/download/v0.0.13/alpaca_0.0.13_linux_arm64.tar.gz"
      sha256 "2cfa613bfed46736e7aac37a2a53eda2fe255557e47c65807c388a94a5d7d2bf"
      def install
        bin.install "alpaca"
      end
    end
  end
end
